# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170219_1302'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='profile',
            order_with_respect_to='user',
        ),
    ]
