# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170219_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='profile',
            order_with_respect_to=None,
        ),
    ]
