# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170219_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_account',
            field=models.CharField(blank=True, default=2, max_length=20),
            preserve_default=False,
        ),
    ]
