# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170221_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_birthday',
            field=models.BooleanField(default=True),
        ),
    ]
