# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_show_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='pic_folder/thumbnails/'),
        ),
    ]
