# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_thumbnail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_account',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=profiles.models.image_path),
        ),
    ]
