# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to=profiles.models.image_path)),
                ('show_email', models.BooleanField(default=True)),
                ('show_birthday', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
