# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0002_project_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='link',
        ),
    ]
