# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 12:04
from __future__ import unicode_literals

from django.db import migrations
from menu.models import validate_season, get_season_from_date
from django.core.exceptions import ValidationError


def change_datetime_to_date(apps, schema_editor):
    Menu = apps.get_model("menu", "Menu")
    Item = apps.get_model("menu", "Item")
    for menu in Menu.objects.all():
        menu.created_date_new = menu.created_date.date()
        if hasattr(menu, 'expiration_date') and menu.expiration_date:
            menu.expiration_date_new = menu.expiration_date.date()
        try:
            validate_season(menu.season)
        except ValidationError:
            if hasattr(menu, 'expiration_date') and menu.expiration_date:
                menu.season = get_season_from_date(menu.expiration_date)
            else:
                menu.season = get_season_from_date(menu.created_date)
        menu.save()
    for item in Item.objects.all():
        item.created_date_new = item.created_date.date()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170427_0503'),
    ]

    operations = [
        migrations.RunPython(change_datetime_to_date),
    ]
