# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170427_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(help_text="please provide a season and a year: possible seasons are ''Autumn', 'Fall' 'Hot, 'Cool, 'Summer', 'Spring' 'Winter', 'Allyear'", max_length=20, validators=[menu.models.validate_season], verbose_name='Season'),
        ),
    ]
