# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0003_auto_20170627_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='teambuilder.Project'),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='teambuilder.Skill'),
        ),
    ]
