# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0004_auto_20170627_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='teambuilder.Position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('0', 'Undecided'), ('a', 'Approved'), ('r', 'Rejected')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='teambuilder.Project'),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='teambuilder.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant_requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_timeline',
            field=models.TextField(),
        ),
    ]
