# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='userdog',
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.ImageField(upload_to='pugorugh/static/images/dogs'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge')], max_length=2, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'liked'), ('d', 'disliked')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge')], max_length=50),
        ),
    ]
