# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20170604_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=50, verbose_name='Age Preference List'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='f,m', max_length=50, verbose_name='Gender Preference List'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', max_length=50, verbose_name='Size Preference List'),
        ),
    ]
