# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-08 09:50
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20170607_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge')], max_length=50),
        ),
    ]
