# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20170604_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=50, verbose_name='Age Preference List'),
        ),
    ]
