# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0007_auto_20170604_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge'), ('u', 'unknown'), ('u', 'unknown')], max_length=2, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'liked'), ('d', 'disliked'), ('u', 'unknown')], max_length=1, verbose_name='Status'),
        ),
    ]
