# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-05 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0009_auto_20170604_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='dog',
            name='userdog',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
