# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0010_auto_20170605_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_class',
            field=models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='b', max_length=1, verbose_name='Age'),
        ),
    ]
