# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0011_dog_age_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age_class',
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge'), ('u', 'unknown')], max_length=50),
        ),
    ]
