# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AddField(
            model_name='item',
            name='created_date_new',
            field=models.DateField(default=datetime.date(2017, 4, 27)),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_date_new',
            field=models.DateField(default=datetime.date(2017, 4, 27)),
        ),
        migrations.AddField(
            model_name='menu',
            name='expiration_date_new',
            field=models.DateField(blank=True, help_text='when will this menu expire?', null=True, validators=[menu.models.validate_not_in_the_past], verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 12, 3, 22, 844792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 12, 3, 22, 843570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(help_text='please chose some items', related_name='items', to='menu.Item'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(help_text='please provide a name', max_length=20, verbose_name='Season'),
        ),
    ]
