# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170427_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date',
        ),
        migrations.RenameField('menu', 'created_date_new', 'created_date'),
        migrations.RenameField('item', 'created_date_new', 'created_date'),
        migrations.RenameField('menu', 'expiration_date_new', 'expiration_date'),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='when will this menu expire?', null=True, validators=[menu.models.validate_not_in_the_past], verbose_name='Expiration Date'),
        ),
    ]
